services:
  - type: web
    name: pg-management-backend
    env: python
    plan: free
    buildCommand: pip install -r pg_managementPRD/requirements.txt
    startCommand: gunicorn pg_managementPRD.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pg_managementPRD.settings
      - key: PYTHON_VERSION
        value: 3.11
